spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pl_football
    username: usol
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: temp/study/study_uploaded_files
  mvc:
    static-path-pattern: /webapp/**

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace